package tmpl

const WelcomeMessage = "welcome.tpl"
const Commands = "commands.tpl"
const ErrorMessage = "error.tpl"
const PasswordPrompt = "password_prompt.tpl"
const PasswordTooShort = "password_too_short.tpl"
const PasswordSetFailed = "password_set_failed.tpl"
const PasswordSetSuccess = "password_set_success.tpl"
const EmailPrompt = "email_prompt.tpl"
const InvalidEmail = "invalid_email.tpl"
const EmailUpdateFailed = "email_update_failed.tpl"
const EmailUpdateSuccess = "email_update_success.tpl"
const PasswordAlreadySet = "password_already_set.tpl"
const RefreshChatFailed = "refresh_chat_failed.tpl"
const RefreshChatSuccess = "refresh_chat_success.tpl"
